### ISSUE TITLE
Can you share your training loss log for Mistral-ORPO-β (7B)?

### ISSUE THREAD

**Issue by yechenzhi** [xfactlab/orpo#26]
I implemented lora ORPO myself using [Torchtune](https://github.com/pytorch/torchtune). However, I'm unsure if it's correct, and the loss curve appears somewhat irregular. Therefore, I'd like to compare it with yours to see if they align.
my version(not finished training):
loss and policy_nll_loss:
![image](https://github.com/xfactlab/orpo/assets/18010625/55e21e4f-bcc7-4ce2-b5ac-a37f33f2e969)
ORPO loss:
![image](https://github.com/xfactlab/orpo/assets/18010625/64430b81-657b-45d0-a7e0-a638f7ec45b7)

**Comment by jiwooya1000** [comment]
Hello @yechenzhi,
for better reproducibility, I just trained `Mistral-orpo-beta` with [alignment-handbook](https://github.com/huggingface/alignment-handbook).
All you need to do is make a new `.yaml` file like this example of [Zephyr-ORPO-141B](https://github.com/huggingface/alignment-handbook/blob/main/recipes/zephyr-141b-A35b/orpo/config_full.yaml).

The corresponding .yaml file will look like this (you could fill in `hub_model_id` and `output_dir` with your values).
```
# Model arguments
model_name_or_path: mistralai/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  argilla/ultrafeedback-binarized-preferences-cleaned: 1.0
dataset_splits:
- train
preprocessing_num_workers: 48

# ORPOTrainer arguments
bf16: true
beta: 0.1
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id:   
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1792
num_train_epochs: 3 
optim: paged_adamw_8bit
output_dir: 
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
hub_private_repo: True
```

And the resulting training log will look like this (MT-Bench was 7.325 with this checkpoint, which aligns with the one reported in the paper):
![image](https://github.com/xfactlab/orpo/assets/20739007/131a665b-3a4b-4c38-932f-9707dcdaae1b)

Hope this could be help you comparing the results🙂

**Comment by qingquansong** [comment]
Hey @jiwooya1000 thank you for providing the repo! I'm trying to follow the instruction to use alignment handbook to reproduce and with same config + 4GPUs (the reason I choose 4 is because I saw you have 
~2850 steps in total (3 epochs) so with the training batch size 8 per gpu and grad accumulation 2 and 60.8k samples, it will  roughly take 950 step per epoch) However, after finish the training, the mt-bench results at my side is `Turn1 - 7.21, Turn 2 - 5.95`. One more change I have is the optimizer as there're some dependency issue of using 8bit optimizer, I switch to use the 32bit original torch AdamW optimizer. The losses and log ads ratio I got is below which seems to be much smaller than the one you shown I the end for each:

<img width="1398" alt="Screenshot 2024-05-23 at 4 26 44 PM" src="https://github.com/xfactlab/orpo/assets/25535036/7ded785f-7d87-4371-b66f-1d79dd06e3e4">
![Screenshot 2024-05-23 at 4 42 48 PM](https://github.com/xfactlab/orpo/assets/25535036/e6d3ac89-67d3-4806-a505-77ed3a134b8a)
![Screenshot 2024-05-23 at 4 50 20 PM](https://github.com/xfactlab/orpo/assets/25535036/c837c5db-9ad6-4440-9b40-5dd261195718)


My config is below. Any further instruction to share to reproduce the model? Thank you very much!

```

# Model arguments
model_name_or_path: mistralai/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  argilla/ultrafeedback-binarized-preferences-cleaned: 1.0
dataset_splits:
- train
preprocessing_num_workers: 128

# ORPOTrainer arguments
bf16: true
beta: 0.1
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: mistral-7b-orpo-beta
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1792
num_train_epochs: 3 
optim: adamw_torch
output_dir: /alignment_handbook_models/mistral-7b-orpo-beta3
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42
hub_private_repo: false
```
